#cloud-config

# Create an empty file on the system
write_files:
- path: /root/CLOUD_INIT_WAS_HERE

# Run a few commands (update apt's repo indexes and install curl)
runcmd:
  - cd /root/
  - echo "Done" >> ~/vm-setup.log
